[package]
name = "trionchain-node"
version = "4.0.0-dev"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
homepage = "https://substrate.io/"
edition.workspace = true
license = "MIT-0"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
build = "build.rs"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "trionchain-node"
[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
futures = { version = "0.3.21", features = ["thread-pool"] }
serde_json = "1.0.111"

sc-cli = { path = "../deps/polkadot-sdk/substrate/client/cli" }
sp-core = { path = "../deps/polkadot-sdk/substrate/primitives/core" }
sc-executor = { path = "../deps/polkadot-sdk/substrate/client/executor" }
sc-network = { path = "../deps/polkadot-sdk/substrate/client/network" }
sc-service = { path = "../deps/polkadot-sdk/substrate/client/service" }
sc-telemetry = { path = "../deps/polkadot-sdk/substrate/client/telemetry" }
sc-transaction-pool = { path = "../deps/polkadot-sdk/substrate/client/transaction-pool" }
sc-transaction-pool-api = { path = "../deps/polkadot-sdk/substrate/client/transaction-pool/api" }
sc-offchain = { path = "../deps/polkadot-sdk/substrate/client/offchain" }
sc-consensus-aura = { path = "../deps/polkadot-sdk/substrate/client/consensus/aura" }
sp-consensus-aura = { path = "../deps/polkadot-sdk/substrate/primitives/consensus/aura" }
sc-consensus = { path = "../deps/polkadot-sdk/substrate/client/consensus/common" }
sc-consensus-grandpa = { path = "../deps/polkadot-sdk/substrate/client/consensus/grandpa" }
sp-consensus-grandpa = { path = "../deps/polkadot-sdk/substrate/primitives/consensus/grandpa" }
sc-client-api = { path = "../deps/polkadot-sdk/substrate/client/api" }
sp-runtime = { path = "../deps/polkadot-sdk/substrate/primitives/runtime" }
sp-io = { path = "../deps/polkadot-sdk/substrate/primitives/io" }
sp-timestamp = { path = "../deps/polkadot-sdk/substrate/primitives/timestamp" }
sp-inherents = { path = "../deps/polkadot-sdk/substrate/primitives/inherents" }
sp-keyring = { path = "../deps/polkadot-sdk/substrate/primitives/keyring" }
frame-system = { path = "../deps/polkadot-sdk/substrate/frame/system" }
pallet-transaction-payment = { path = "../deps/polkadot-sdk/substrate/frame/transaction-payment", default-features = false }

# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.16.2", features = ["server"] }
sp-api = { path = "../deps/polkadot-sdk/substrate/primitives/api" }
sc-rpc-api = { path = "../deps/polkadot-sdk/substrate/client/rpc-api" }
sp-blockchain = { path = "../deps/polkadot-sdk/substrate/primitives/blockchain" }
sp-block-builder = { path = "../deps/polkadot-sdk/substrate/primitives/block-builder" }
sc-basic-authorship = { path = "../deps/polkadot-sdk/substrate/client/basic-authorship" }
substrate-frame-rpc-system = { path = "../deps/polkadot-sdk/substrate/utils/frame/rpc/system" }
pallet-transaction-payment-rpc = { path = "../deps/polkadot-sdk/substrate/frame/transaction-payment/rpc" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { path = "../deps/polkadot-sdk/substrate/frame/benchmarking" }
frame-benchmarking-cli = { path = "../deps/polkadot-sdk/substrate/utils/frame/benchmarking-cli" }

# Local Dependencies
trionchain-runtime = { path = "../runtime", features = ["std"] }

# CLI-specific dependencies
try-runtime-cli = { path = "../deps/polkadot-sdk/substrate/utils/frame/try-runtime/cli", optional = true }

[build-dependencies]
substrate-build-script-utils = { path = "../deps/polkadot-sdk/substrate/utils/build-script-utils" }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"frame-system/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
	"try-runtime-cli/try-runtime",
]
